const animeData = [
    {
			"englishTitle": "Cowboy Bebop",
			"romajiTitle": "Cowboy Bebop",
      "nativeTitle": "カウボーイビバップ",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Enter a world in the distant future, where Bounty Hunters roam the solar system. Spike and Jet, bounty hunting partners, set out on journeys in an ever struggling effort to win bounty rewards to survive.<br><br>\nWhile traveling, they meet up with other very interesting people. Could Faye, the beautiful and ridiculously poor gambler, Edward, the computer genius, and Ein, the engineered dog be a good addition to the group?",
      "startDate": "4/3/1998",
      "endDate": "4/24/1999",
      "season": "SPRING",
      "episodes": 26,
      "duration": 24,
      "source": "ORIGINAL",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx1-CXtrrkMpJ8Zq.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx1-CXtrrkMpJ8Zq.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/1-T3PJUjFJyRwg.jpg",
      "genres": [
        "Action",
        "Adventure",
        "Drama",
        "Sci-Fi"
      ],
      "studio": "Sunrise"
    },
    {
			"englishTitle": "Trigun",
			"romajiTitle": "TRIGUN",
      "nativeTitle": "TRIGUN",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Vash the Stampede is a wanted man with a habit of turning entire towns into rubble. The price on his head is a fortune, and his path of destruction reaches across the arid wastelands of a desert planet. Unfortunately, most encounters with the spiky-haired gunslinger don't end well for the bounty hunters who catch up with him; someone almost always gets hurt - and it's never Vash.<br>\n<br>\nOddly enough, for such an infamous fugitive, there's no proof that he's ever taken a life. In fact, he's a pacifist with a doughnut obsession who's more doofus than desperado. There's a whole lot more to him than his reputation lets on - Vash the Stampede definitely ain't your typical outlaw.<br>\n<br>\n(Source: Funimation)",
      "startDate": "4/1/1998",
      "endDate": "9/30/1998",
      "season": "SPRING",
      "episodes": 26,
      "duration": 24,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx6-YzcO3EcioJJS.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx6-YzcO3EcioJJS.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/6-4pIR2RY8AHZ0.jpg",
      "genres": [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Sci-Fi"
      ],
      "studio": "MADHOUSE"
    },
    {
			"englishTitle": "Witch Hunter ROBIN",
			"romajiTitle": "Witch Hunter ROBIN",
      "nativeTitle": "Witch Hunter ROBIN",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Robin Sena is a powerful craft user drafted into the STNJ - a group of specialized hunters that fight deadly beings known as Witches. Though her fire power is great, she’s got a lot to learn about her powers and working with her cool and aloof partner, Amon. But the truth about the Witches and herself will leave Robin on an entirely new path that she never expected!<br>\n<br>\n(Source: Funimation)",
      "startDate": "7/2/2002",
      "endDate": "12/24/2002",
      "season": "SUMMER",
      "episodes": 26,
      "duration": 25,
      "source": "ORIGINAL",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx7-6uh1fPvbgS9t.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx7-6uh1fPvbgS9t.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/7-hjjlCe3yO7lO.jpg",
      "genres": [
        "Action",
        "Drama",
        "Mystery",
        "Supernatural"
      ],
      "studio": "Sunrise"
    },
    {
      "englishTitle": "Beet the Vandel Buster",
      "romajiTitle": "Bouken Ou Beet",
      "nativeTitle": "冒険王ビィト",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "It is the dark century and the people are suffering under the rule of the devil, Vandel, who is able to manipulate monsters. The Vandel Busters are a group of people who hunt these devils, and among them, the Zenon Squad is known to be the strongest busters on the continent. A young boy, Beet, dreams of joining the Zenon Squad. However, one day, as a result of Beet's fault, the Zenon squad was defeated by the devil, Beltose. The five dying busters sacrificed their life power into their five weapons, Saiga. After giving their weapons to Beet, they passed away. Years have passed since then and the young Vandel Buster, Beet, begins his adventure to carry out the Zenon Squad's will to put an end to the dark century. ",
      "startDate": "9/30/2004",
      "endDate": "9/29/2005",
      "season": "FALL",
      "episodes": 52,
      "duration": 23,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/b8-ReS3TwSgrDDi.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/b8-ReS3TwSgrDDi.jpg",
      "bannerImage": null,
      "genres": [
        "Adventure",
        "Fantasy",
        "Supernatural"
      ],
      "studio": "Toei Animation"
    },
    {
			"englishTitle": "Eyeshield 21",
			"romajiTitle": "Eyeshield 21",
      "nativeTitle": "アイシールド21",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Welcome To the Gridiron of the Damned!   Huge hulking bodies throw themselves at each other, while a tiny lithe body runs between them for the goal!  No, it&rsquo;s not a game of football, it&rsquo;s Sena Kobayakawa trying to evade the monstrous Ha-Ha brothers down the halls of Deimon High School!  But wait!  Sena&rsquo;s incredible skills at not getting caught have been spotted by the devilish (possibly actually demonic) captain of the school&rsquo;s embryonic American style football team, and when Sena asks to be the teams manager, he gets  thrust onto the field as a running back instead!  But there are two BIG catches: first, to keep the identity of their new &ldquo;star&rdquo; player an absolute secret, Yoichi makes Sena wear an opaque visor on his helmet and gives him the alias of &ldquo;Eyeshield 21.&rdquo;  And the second catch?  Well, in order to hit his fastest &ldquo;speed of light&rdquo; running mode, Sena usually has to be absolutely terrified. Not that THAT will be a problem with the monstrous players that he&rsquo;ll soon find himself running from!  The insanity hits the streets when the feet meet the cleats in EYESHIELD 21! <br><br>\n(Source: Sentai Filmworks)",
      "startDate": "4/6/2005",
      "endDate": "3/19/2008",
      "season": "SPRING",
      "episodes": 145,
      "duration": 23,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx15-A4F2t0TgWoi4.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx15-A4F2t0TgWoi4.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/n15-1eTutXlxYzYl.jpg",
      "genres": [
        "Action",
        "Comedy",
        "Sports"
      ],
      "studio": "Sentai Filmworks"
    },
    {
			"englishTitle": "Honey and Clover",
			"romajiTitle": "Hachimitsu to Clover",
      "nativeTitle": "ハチミツとクローバー",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Takemoto Yuuta, Mayama Takumi, and Morita Shinobu are college students who share the small apartment. Even though they live in poverty, the three of them are able to obtain pleasure through small things in life. The story follows these characters' life stories as poor college students, as well as their love lives when a short but talented 18 year old girl called Hanamoto Hagumi appears.\n<br><br>\n(Source: Anime News Network)",
      "startDate": "4/15/2005",
      "endDate": "9/27/2005",
      "season": "SPRING",
      "episodes": 24,
      "duration": 23,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx16-5fJZ2Sy2ThRA.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx16-5fJZ2Sy2ThRA.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/16-jmEaCBBN5WRS.jpg",
      "genres": [
        "Comedy",
        "Drama",
        "Romance",
        "Slice of Life"
      ],
      "studio": "Viz Media"
    },
    {
      "englishTitle": "Hungry Heart: Wild Striker",
			"romajiTitle": "Hungry Heart: Wild Striker",
      "nativeTitle": "ハングリーハート Wild Striker",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Kyosuke Kano has lived under the shadow of his successful brother Seisuke all his life who is a professional soccer player. Tired of being compared and downgraded at, he abandoned playing soccer until a boy from his new highschool discovered him and asked him to join their team. Kyosuke joins it and befriends two other first year players named Rodrigo and Sakai with the dream of becomming professional soccer players themselves.\n<br><br>\n(Source: Anime News Network)",
      "startDate": "9/11/2002",
      "endDate": "9/10/2003",
      "season": "FALL",
      "episodes": 52,
      "duration": 23,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx17-6kqIbdUk3dgi.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx17-6kqIbdUk3dgi.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/17-2drlTPxc3WTh.png",
      "genres": [
        "Comedy",
        "Slice of Life",
        "Sports"
      ],
      "studio": "Nippon Animation"
    },
    {
			"englishTitle": "Initial D 4th Stage",
			"romajiTitle": "Initial D FOURTH STAGE",
      "nativeTitle": "頭文字〈イニシャル〉D FOURTH STAGE",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Takumi Fujiwara and brothers Keisuke and Ryousuke Takahashi have formed \"Project D,\" a racing team aimed at bringing their driving skills to their full potential outside their prefecture. Using the internet, Project D issues challenges to other racing teams and posts results of their races. Managed by Ryousuke, the team has Takumi engaging in downhill battles with his AE86, while Keisuke challenges opponents uphill. Among their rivals are the Seven-Star Leaf (SSR) and Todo-juku.",
      "startDate": "4/17/2004",
      "endDate": "2/18/2006",
      "season": "SPRING",
      "episodes": 24,
      "duration": 27,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/b18-r7IirVmwP89u.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/b18-r7IirVmwP89u.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/18-aiibhi4BrZeR.jpg",
      "genres": [
        "Action",
        "Drama",
        "Sports"
      ],
      "studio": "Funimation"
    },
    {
      "englishTitle": "Monster",
      "romajiTitle": "MONSTER",
      "nativeTitle": "MONSTER",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Dr. Kenzo Tenma is a renowned Japanese brain surgeon working at a leading hospital in Germany. One night, Dr. Tenma risks his reputation and career to save the life of a critically wounded young boy over that of the town mayor who had been planning to support the hospital financially. A string of mysterious murders begin to occur soon after the operation, and Dr. Tenma emerges as the primary suspect despite no incriminating evidence. \n<br><br>\nA doctor is taught to believe that all life is equal; however, when another series of murders occur in the surgeon's vicinity, Dr. Tenma's beliefs are shaken as his actions that night are shown to have much broader consequences than he could have imagined. Leaving behind his life as a surgeon he embarks on a journey across the country to unravel the mystery of the boy he saved.",
      "startDate": "4/7/2004",
      "endDate": "9/28/2005",
      "season": "SPRING",
      "episodes": 74,
      "duration": 24,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/nx19-95nNPzaSr2V5.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/nx19-95nNPzaSr2V5.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/19-kJhwsB0Z97tL.jpg",
      "genres": [
        "Drama",
        "Horror",
        "Mystery",
        "Psychological",
        "Thriller"
      ],
      "studio": "MADHOUSE"
    },
    {
			"englishTitle": "Naruto",
			"romajiTitle": "NARUTO",
      "nativeTitle": "NARUTO -ナルト-",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Naruto Uzumaki, a hyperactive and knuckle-headed ninja, lives in Konohagakure, the Hidden Leaf village. Moments prior to his birth, a huge demon known as the Kyuubi, the Nine-tailed Fox, attacked Konohagakure and wreaked havoc. In order to put an end to the Kyuubi's rampage, the leader of the village, the 4th Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. <br><br>\nShunned because of the presence of the Kyuubi inside him, Naruto struggles to find his place in the village. He strives to become the Hokage of Konohagakure, and he meets many friends and foes along the way. <br><br>\n(Source: MAL Rewrite)",
      "startDate": "10/3/2002",
      "endDate": "2/8/2007",
      "season": "FALL",
      "episodes": 220,
      "duration": 23,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx20-E3YH5W6sz6H7.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx20-E3YH5W6sz6H7.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/20-HHxhPj5JD13a.jpg",
      "genres": [
        "Action",
        "Comedy"
      ],
      "studio": "Aniplex"
    },
    {
			"englishTitle": "ONE PIECE",
			"romajiTitle": "ONE PIECE",
      "nativeTitle": "ONE PIECE",
      "type": "ANIME",
      "format": "TV",
      "status": "RELEASING",
      "description": "Gold Roger was known as the Pirate King, the strongest and most infamous being to have sailed the Grand Line. The capture and death of Roger by the World Government brought a change throughout the world. His last words before his death revealed the location of the greatest treasure in the world, One Piece. It was this revelation that brought about the Grand Age of Pirates, men who dreamed of finding One Piece (which promises an unlimited amount of riches and fame), and quite possibly the most coveted of titles for the person who found it, the title of the Pirate King.<br><br>\nEnter Monkey D. Luffy, a 17-year-old boy that defies your standard definition of a pirate. Rather than the popular persona of a wicked, hardened, toothless pirate who ransacks villages for fun, Luffy’s reason for being a pirate is one of pure wonder; the thought of an exciting adventure and meeting new and intriguing people, along with finding One Piece, are his reasons of becoming a pirate. Following in the footsteps of his childhood hero, Luffy and his crew travel across the Grand Line, experiencing crazy adventures, unveiling dark mysteries and battling strong enemies, all in order to reach One Piece.<br><br>\n<b>*This includes following special episodes:<\/b><br>\n- Chopperman to the Rescue! Protect the TV Station by the Shore! (Episode 336)<br>\n- The Strongest Tag-Team! Luffy and Toriko's Hard Struggle! (Episode 492)<br>\n- Team Formation! Save Chopper (Episode 542)<br>\n- History's Strongest Collaboration vs. Glutton of the Sea (Episode 590)<br>\n- 20th Anniversary! Special Romance Dawn (Episode 907)",
      "startDate": "10/20/1999",
      "endDate": null,
      "season": "FALL",
      "episodes": null,
      "duration": 24,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/nx21-tXMN3Y20PIL9.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/nx21-tXMN3Y20PIL9.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/21-wf37VakJmZqs.jpg",
      "genres": [
        "Action",
        "Adventure",
        "Comedy",
        "Drama",
        "Fantasy"
      ],
      "studio": "Toei Animation"
    },
    {
			"englishTitle": "The Prince of Tennis",
			"romajiTitle": "Tennis no Ouji-sama",
      "nativeTitle": "テニスの王子様",
    "type": "ANIME",
    "format": "TV",
    "status": "FINISHED",
    "description": "Echizen Ryoma is a young tennis prodigy who has won 4 consecutive tennis championships but who constantly lies in the shadow of his father, a former pro tennis player. He joins the Seishun Gakuen junior highschool, one of the best tennis schools in Japan, and there along with his teamates he learns to find his own type of tennis in an attempt to defeat his biggest obstacle of all: his father as well as himself.\n<br><br>\n(Source: Anime News Network)",
    "startDate": "10/10/2001",
    "endDate": "3/23/2005",
    "season": "FALL",
    "episodes": 178,
    "duration": 22,
    "source": "MANGA",
    "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx22-8Qg3NZXH6asP.png",
    "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx22-8Qg3NZXH6asP.png",
    "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/22-wVJjA9tGMt4k.jpg",
    "genres": [
      "Action",
      "Comedy",
      "Sports"
    ],
    "studio": "Production I.G"
    },
    {
			"englishTitle": "Ring ni Kakero 1",
			"romajiTitle": "Ring ni Kakero 1",
      "nativeTitle": "リングにかけろ１",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "In order to fulfill their dead father's wish, the siblings, Takane Kiku and Takane Ryuji aims for the champopn title of the boxing arena. The sister, Kiku, will act as the trainer while her brother, Ryuji, will concentrate on the role of the boxer and learn the Boomerang. His battle with many rivals has led to the growth and maturity of Ryuji. The junior high boxing tournament has began and Ryuji will be fighting with his arch-rival, Kenzaki Jun. The battle begins.\n<br><br>\n(Source: Anime News Network)",
      "startDate": "10/6/2004",
      "endDate": "12/15/2004",
      "season": "FALL",
      "episodes": 12,
      "duration": 25,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/23.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/23.jpg",
      "bannerImage": null,
      "genres": [
        "Action",
        "Sports"
      ],
      "studio": "Toei Animation"
    },
    {
      "englishTitle": "School Rumble",
			"romajiTitle": "School Rumble",
      "nativeTitle": "スクールランブル",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Tsukamoto Tenma is an ordinary 2nd year high school student who has fallen in love with one of her classmates, Karasuma Ooji. However, currently she is unable to confess her feelings to him. To make things worse, she found out that Karasuma is transferring to another school in a year. On the other hand, Tenma's other classmate, Harima Kenji (who is a delinquent) is also in love with Tenma. Not being able to confess his feelings, Harima gets depressed day by day.<br><br>\n(Source: Anime News Network)",
      "startDate": "10/5/2004",
      "endDate": "3/29/2005",
      "season": "FALL",
      "episodes": 26,
      "duration": 23,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx24-xxnI0WU9UTkF.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx24-xxnI0WU9UTkF.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/24-THD6AYmlVPIb.jpg",
      "genres": [
        "Comedy",
        "Romance",
        "Slice of Life"
      ],
      "studio": "Funimation"
    },
    {
			"englishTitle": "Desert Punk",
			"romajiTitle": "Sunabouzu",
      "nativeTitle": "砂ぼうず",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "In the future, Japan is a wasteland. In the Great Kantou Desert, scattered humans eke out a living in the hot sand. Among them, a short-statured man they call \"Sunabouzu\" makes a living as a bounty hunter. Like a demon of the sand, he seems unbeatable. Yet, like all men, he has a particular weakness for the opposite sex... <br><br>\n(Source: Anime News Network)",
      "startDate": "10/6/2004",
      "endDate": "3/30/2005",
      "season": "FALL",
      "episodes": 24,
      "duration": 24,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx25-H1etX7IgfFtQ.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx25-H1etX7IgfFtQ.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/25-F2qEJ3hvFzHj.jpg",
      "genres": [
        "Action",
        "Adventure",
        "Comedy",
        "Ecchi",
        "Sci-Fi"
      ],
      "studio": "Funimation"
    },
    {
			"englishTitle": "Texhnolyze",
			"romajiTitle": "TEXHNOLYZE",
      "nativeTitle": "TEXHNOLYZE",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "In a man-made underground society, descendants of a banished generation vie for control of the crumbling city of Lux. Ichise, an orphan turned prize fighter, loses a leg and an arm to satisfy an enraged fight promoter. On the brink of death he is taken in by a young woman doctor and used as a guinea pig for the next evolution of Texhnolyze. With his new limbs, Ichise is taken under the wing of Oonishi, a powerful leader of Organ, an organization with some hold on Lux. As Ichise is drawn deeper into a war for territorial control of the city, he learns of his possible future from the young girl prophet Ran, who guides him from the shadows in his darkest times. With the explosion of the warfare, Ichise must uncover the truth about Lux and fight for his survival as he realizes his destiny.\n<br><br>\n(Source: Anime News Network)",
      "startDate": "4/17/2003",
      "endDate": "9/25/2003",
      "season": "SPRING",
      "episodes": 22,
      "duration": 23,
      "source": "ORIGINAL",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx26-u2SawALYH3w3.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx26-u2SawALYH3w3.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/26-FWJgAONj7etr.jpg",
      "genres": [
        "Action",
        "Drama",
        "Psychological",
        "Sci-Fi"
      ],
      "studio": "MADHOUSE"
    },
    {
			"englishTitle": "Trinity Blood",
			"romajiTitle": "Trinity Blood",
      "nativeTitle": "トリニティ・ブラッド",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "The background is in the distant future after the destruction brought about by Armageddon. The war between the vampires and the humans continue to persist. In order to protect the humans from the vampires, the Vatican has to rely on other allies to counter the situation. The protagonist,  Abel Nightroad, is a traveling priest from the Vatican and a crusnik, a vampire that drinks the blood of vampires. He is a member of the \"Ax\", a special operations group led by Cardinal Catherina Sforza. He encounters a young girl called Esther, who decides to go with him to Rome and train at the Vatican. Soon after he meets her, the order of Rozencreuz, led by Abel's twin, Cain, tries to continue the war so they can rule the world. It's up to Abel and the AX to try and stop them.",
      "startDate": "4/29/2005",
      "endDate": "10/28/2005",
      "season": "SPRING",
      "episodes": 24,
      "duration": 24,
      "source": "LIGHT_NOVEL",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx27-MOAaiBHHLfOY.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx27-MOAaiBHHLfOY.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/27-33qla7duy3Gq.jpg",
      "genres": [
        "Action",
        "Drama",
        "Horror",
        "Sci-Fi",
        "Supernatural"
      ],
      "studio": "Funimation"
    },
    {
      "englishTitle": "Yakitate!! Japan",
      "nativeTitle": "焼きたて!! ジャぱん",
			"romajiTitle": "Yakitate!! Japan",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Kazuma Azuma wants to make bread. Not just any kind of bread, though. He wants to make a bread that represents Japan itself and can stand toe-to-toe with rice as a national food. Thanks to his legendary \"Hands of the Sun,\" unnaturally warm hands that allow dough to ferment faster, Kazuma's bread is like a slice of Heaven.<br>\n<br>\nAnd when the Pantasia Rookie Competition arrives, everyone will get a taste of his skill! Along with his friend Kawachi (who's only in it for the dough), he’ll go up against koala karate masters, Harvard bread scientists, samurai with rolling-pin swords, and more! Can Kazuma create bread like naan other and bake his way to glory, or should he quit before he's toast?<br>\n<br>\n(Source: Right Stuf)",
      "startDate": "10/12/2004",
      "endDate": "3/14/2006",
      "season": "FALL",
      "episodes": 69,
      "duration": 24,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx28-QuKcZpUjTXzV.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx28-QuKcZpUjTXzV.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/28-XGCH1SoNhyiC.jpg",
      "genres": [
        "Comedy"
      ],
      "studio": "Sunrise"
    },
    {
      "englishTitle": "Zipang",
			"romajiTitle": "Zipang",
      "nativeTitle": "ジパング",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Mirai, an improved Kongou-class Aegis guided missile destroyer, is one of the newest and most advanced ships in the entire Japanese Self Defense Force (SDF). Her crew, also one of the newest, is lead by Capt. Umezu Saburo and Executive Officer Kadomatsu Yosuke. While running scheduled training exercises one day, Mirai encounters a fierce storm that throws their navigation systems into temporary disarray. After a few minutes of recovery, the crew is shocked to discover that they've been transported back in time to June 4, 1942&mdash;The Battle of Midway, during World War II. Letting history take its course for this battle, they manage to avoid the conflict firsthand and make a vow to remain annonymous, changing history as little as possible. However, when the crew comes across the dying Lt. Commander Kusaka Takumi, XO. Kadomatsu's instincts to save lives takes over, changing the course of history more than he could've imagined.\n<br><br>\n(Source: Anime News Network)",
      "startDate": "10/7/2004",
      "endDate": "3/31/2005",
      "season": "FALL",
      "episodes": 26,
      "duration": 24,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx29-0PsnJVadMG7k.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx29-0PsnJVadMG7k.jpg",
      "bannerImage": null,
      "genres": [
        "Action",
        "Sci-Fi"
      ],
      "studio": "Studio DEEN"
    },
    {
			"englishTitle": "Neon Genesis Evangelion",
			"romajiTitle": "Shin Seiki Evangelion",
      "nativeTitle": "新世紀エヴァンゲリオン",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "In the year 2015, the Angels, huge, tremendously powerful, alien war machines, appear in Tokyo for the second time. The only hope for Mankind's survival lies in the Evangelion, a humanoid fighting machine developed by NERV, a special United Nations agency. Capable of withstanding anything the Angels can dish out, the Evangelion's one drawback lies in the limited number of people able to pilot them. Only a handful of teenagers, all born fourteen years ago, nine months after the Angels first appeared, are able to interface with the Evangelion. One such teenager is Shinji Ikari, whose father heads the NERV team that developed and maintains the Evangelion. Thrust into a maelstrom of battle and events that he does not understand, Shinji is forced to plumb the depths of his own inner resources for the courage and strength to not only fight, but to survive, or risk losing everything. <br><br>\n(Source: AniDB)<br>\n<br>\n <i>Note: Later releases include edited versions of Episodes 21-24 called the \"Director's Cut\" with some visual editing and adding extra scenes that appeared in the theatrical recap 'Death'.<\/i>",
      "startDate": "10/3/1995",
      "endDate": "3/27/1996",
      "season": "FALL",
      "episodes": 26,
      "duration": 24,
      "source": "ORIGINAL",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx30-1Ro1NFFg28bu.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx30-1Ro1NFFg28bu.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/30-gEMoHHIqxDgN.jpg",
      "genres": [
        "Action",
        "Drama",
        "Mecha",
        "Mystery",
        "Psychological",
        "Sci-Fi"
      ],
      "studio": "Kadokawa Shoten"
    },
    {
			"englishTitle": "Berserk",
			"romajiTitle": "Kenpuu Denki Berserk",
      "nativeTitle": "剣風伝奇ベルセルク",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Set during a time that very much resembles Europe during the Middle Ages, <i>Berserk<\/i> is a story of revenge set in the castle town of Midland. Recently, the town has seen the rise of a wicked king, who uses demonic minions to control and victimise his subjects.<br>\n<br>\nHowever, when a lone soldier enters the town calling himself the Black Swordsman and armed to the teeth, many sense that the king's days of unchecked oppression are over. Soon, the Black Swordsman is plying his trade by hunting down the king's evil servants, giving no quarter, and preparing to exact his vengeance on the king.<br>\n<br>\n(Source: MVM Entertainment)",
      "startDate": "10/7/1997",
      "endDate": "3/31/1998",
      "season": "FALL",
      "episodes": 25,
      "duration": 25,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx33-CTtcRjqe7UnM.jpg",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx33-CTtcRjqe7UnM.jpg",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/n33-H5u82ZzMDmKn.jpg",
      "genres": [
        "Action",
        "Adventure",
        "Drama",
        "Fantasy",
        "Horror",
        "Supernatural"
      ],
      "studio": "VAP"
    },
    {
			"englishTitle": "Ghost in the Shell",
			"romajiTitle": "Koukaku Kidoutai",
      "nativeTitle": "攻殻機動隊",
      "type": "ANIME",
      "format": "MOVIE",
      "status": "FINISHED",
      "description": "In the year 2029, the barriers of our world have been broken down by the net and by cybernetics, but this brings new vulnerability to humans in the form of brain-hacking. When a highly-wanted hacker known as the \"Puppet Master\" begins involving them in politics, Section 9, a group of cybernetically enhanced cops, are called in to investigate and stop the Puppet Master. The pursuit will call into question what makes a human and what is the Puppet Master in a world where the distinction between human and machine is increasingly blurry.<br>\n<br>\n(Source: Anime News Network)",
      "startDate": "11/18/1995",
      "endDate": "11/18/1995",
      "season": "FALL",
      "episodes": 1,
      "duration": 83,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx43-gHMR72EkEP4o.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx43-gHMR72EkEP4o.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/43-uDbk1jrG9yod.jpg",
      "genres": [
        "Action",
        "Psychological",
        "Sci-Fi"
      ],
      "studio": "Production I.G"
    },
    {
      "englishTitle": "Samurai X: Trust and Betrayal",
			"romajiTitle": "Rurouni Kenshin: Meiji Kenkaku Romantan - Tsuioku-hen",
      "nativeTitle": "るろうに剣心―明治剣客浪漫譚―追憶編",
      "type": "ANIME",
      "format": "OVA",
      "status": "FINISHED",
      "description": "In the days before the Japanese Revolution, Hiko Seiijuro, a wandering master swordsman and hermit, encounters a bandit raid on a slave wagon. Hiko kills the raiding bandits in hopes of saving as many lives as possible, but only manages to spare one life from the massacre. Hiko leaves the child, advising him to go to the nearby village and have them take care of him. A few days later, as Hiko comes back to check upon the child he saved, he is shocked to see the child had created graves, both for the slaves he befriended and the bandits who killed them. Seeing potential in the young one, Hiko takes the child under his wing, names him Kenshin, meaning \"heart of sword,\" and teaches him about the art of swordsmanship under the Hiten Mitsuruugi Ryu.<br><br>\nStruggling in a constant challenge with his ideal beliefs reflecting against the harshness of reality, Tsuiokuhen tells the melancholic and dark story of Himura Kenshin as one of the most feared assassins of the Japanese Revolution: the Hitokiri Battousai.<br><br>\n[Written by MAL Rewrite]",
      "startDate": "2/20/1999",
      "endDate": "9/22/1999",
      "season": "WINTER",
      "episodes": 4,
      "duration": 30,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx44-MG5I672UbWAy.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx44-MG5I672UbWAy.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/44-C4I2Dy8MMyy0.jpg",
      "genres": [
        "Action",
        "Drama",
        "Romance"
      ],
      "studio": "Aniplex"
    },
    {
      "englishTitle": "Rurouni Kenshin",
			"romajiTitle": "Rurouni Kenshin: Meiji Kenkaku Romantan",
      "nativeTitle": "るろうに剣心 -明治剣客浪漫譚-",
      "type": "ANIME",
      "format": "TV",
      "status": "FINISHED",
      "description": "Himura Kenshin is a vagabond with a dark past and sunny disposition. Not a ronin but a rurouni, he was never a samurai, but an assassin of utmost skill in the Meiji restoration, who in the turning point of the war simply walked away. His travels lead him to Tokyo in the 11th year of the Meiji era, where he befriends a female Kendo master, a former thief, a brawler and a doctor all with their own secrets. Together they fight off the enemies surfacing from the dark past that Kenshin cannot escape. <br><br>\n(Source: Anime News Network)",
      "startDate": "1/10/1996",
      "endDate": "9/8/1998",
      "season": "WINTER",
      "episodes": 94,
      "duration": 25,
      "source": "MANGA",
      "coverImageLarge": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/medium\/bx45-DEFgZRCxiGmF.png",
      "coverImageMedium": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/cover\/small\/bx45-DEFgZRCxiGmF.png",
      "bannerImage": "https:\/\/s4.anilist.co\/file\/anilistcdn\/media\/anime\/banner\/45-JVUpMKU0HzRW.jpg",
      "genres": [
        "Action",
        "Adventure",
        "Comedy",
        "Romance"
      ],
      "studio": "Aniplex"
    }
  ]

module.exports = animeData;